<?php

namespace App\Models;

use CodeIgniter\Model;

class ContractModel extends Model
{
    /**
     * Tanpa DB (sesuai permintaan). Ambil data dari array statis.
     * Jika nanti mau pindah ke DB, cukup ganti method ini.
     */
    public function getAll(): array
    {
        return [
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan Dinas Pendidikan Sulawesi Selatan Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN SGDWIADG WIDGAISGDAW AOUIWDHAOIUWDH AOIDH AWOI AIUHDAIU AWUDOHADUIW',
                'pt'           => 'TMU',
                'pimpro'       => 'Muhammad Fajri Ramdhani wauidhasiduahdiuahd awiudhsaiuahdiuw',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah asuiydgawyudgaw yiauydgaiuywdgawuiy aydgawuydg auydg aukydgawwaydgauk yuyadgau k',
                'status'       => '25 hari lagi libur panjang',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'canceled',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => '60 hari lagi',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
            [
                'institusi'    => 'Dinas Pendidikan Sulawesi Selatan',
                'proyek'       => 'PENGADAAN PERMESINAN PENGGERAK POKOK UNTUK KAPAL NELAYAN',
                'pt'           => 'TMU',
                'pimpro'       => 'M. Fajri Ramdhani',
                'contract'     => '05 Sept 2024',
                'dueDate'      => '09 Okt 2024',
                'deliveryDate' => ' 27 Sept 2024',
                'closeDate'    => '15 Okt 2024',
                'keterangan'   => 'Testing keterangan 123 apa aja lah',
                'status'       => 'completed',
            ],
        ];
    }
}
