<?php

namespace App\Models;

use CodeIgniter\Model;

class PromagModel extends Model
{
    /**
     * Tanpa DB, langsung return array sesuai struktur contoh.
     * Bisa Anda ganti nanti untuk ambil dari DB.
     */
    public function getAll(): array
    {
        return [
            [
                'tanggal' => 'Fri, 19 Jul 2025',
                'judul' => 'Perawatan Steam Boiler;',
                'lokasi' => 'Dinas Pendidikan Sulawesi Selatan;',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'TMU',
                'status' => 'PENDING',
                'progress' => 12,
            ],
            [
                'tanggal' => 'Fri, 26 Jul 2025',
                'judul' => 'Cek Pompa Air',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'OTI',
                'status' => 'ON-PROGRESS',
                'progress' => 55,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            // …lanjutkan item lain sesuai contoh Anda
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
            [
                'tanggal' => 'Fri, 2 Aug 2025',
                'judul' => 'Servis Genset',
                'lokasi' => 'STP Jakarta',
                'penanggung_jawab' => 'Elvin Mudhita',
                'perusahaan' => 'ARI',
                'status' => 'COMPLETED',
                'progress' => 90,
            ],
        ];
    }
}
