<?= $this->extend('layout/template') ?>

<?= $this->section('content') ?>
<div class="content-wrapper">
    <div class="card-pages" id="cardPages"><!-- generated by JS --></div>
</div>
<div class="page-indicators" id="pageIndicators"><!-- generated by JS --></div>

<script>
    window.PROJECTS = <?= json_encode($projects ?? []) ?>;
</script>
<script src="<?= base_url('assets/js/m_loc.js') ?>"></script>
<?= $this->endSection() ?>