<?= $this->extend('layout/template') ?>

<?= $this->section('content') ?>

<div class="content-wrapper-promag">
    <div class="card-pages-promag" id="cardPages"><!-- generated by JS --></div>
</div>

<div class="page-indicators-promag" id="pageIndicators"><!-- generated by JS --></div>

<script>
    // data dari controller
    window.PROJECTS = <?= json_encode($projects ?? []) ?>;

    // pastikan stylesheet halaman adalah promag.css
    document.addEventListener('DOMContentLoaded', () => {
        const el = document.getElementById('page-style');
        if (el) el.href = "<?= esc($pageStyle ?? base_url('assets/css/promag.css')) ?>";
    });
</script>

<!-- JS khusus halaman -->
<script src="<?= base_url('assets/js/promag.js') ?>"></script>

<?= $this->endSection() ?>